package io.github.kotlinreladomo.sample.domain.kotlin.repository

import io.github.kotlinreladomo.core.AbstractBiTemporalRepository
import io.github.kotlinreladomo.sample.domain.kotlin.OrderKt
import org.springframework.stereotype.Repository

/**
 * Repository for Order entities.
 * This is a placeholder - the actual implementation will be generated by the Gradle plugin.
 */
@Repository
interface OrderKtRepository {
    fun save(entity: OrderKt): OrderKt
    fun findById(id: Long): OrderKt?
    fun findByIdAsOf(id: Long, businessDate: java.time.Instant, processingDate: java.time.Instant): OrderKt?
    fun update(entity: OrderKt): OrderKt
    fun deleteById(id: Long)
    fun findAll(): List<OrderKt>
    fun findByCustomerId(customerId: Long): List<OrderKt>
}