-- Create Customers table (non-temporal)
CREATE TABLE IF NOT EXISTS CUSTOMERS (
    CUSTOMER_ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(50),
    ADDRESS VARCHAR(500),
    CREATED_DATE TIMESTAMP NOT NULL
);

-- Create Products table (non-temporal)
CREATE TABLE IF NOT EXISTS PRODUCTS (
    PRODUCT_ID BIGINT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(500),
    PRICE DECIMAL(10,2) NOT NULL,
    STOCK_QUANTITY INT NOT NULL,
    CATEGORY VARCHAR(100)
);

-- Create Orders table (bitemporal)
CREATE TABLE IF NOT EXISTS ORDERS (
    ORDER_ID BIGINT NOT NULL,
    CUSTOMER_ID BIGINT NOT NULL,
    ORDER_DATE TIMESTAMP NOT NULL,
    AMOUNT DECIMAL(10,2) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(500),
    -- Bitemporal columns
    BUSINESS_FROM TIMESTAMP NOT NULL,
    BUSINESS_THRU TIMESTAMP NOT NULL,
    PROCESSING_FROM TIMESTAMP NOT NULL,
    PROCESSING_THRU TIMESTAMP NOT NULL,
    PRIMARY KEY (ORDER_ID, BUSINESS_FROM, PROCESSING_FROM),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

-- Create OrderItems table (non-temporal with composite key)
CREATE TABLE IF NOT EXISTS ORDER_ITEMS (
    ORDER_ITEM_ID BIGINT PRIMARY KEY,
    ORDER_ID BIGINT NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    QUANTITY INT NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    TOTAL_PRICE DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS IDX_ORDERS_CUSTOMER ON ORDERS(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_ORDERS_STATUS ON ORDERS(STATUS);
CREATE INDEX IF NOT EXISTS IDX_ORDERS_TEMPORAL ON ORDERS(BUSINESS_FROM, BUSINESS_THRU, PROCESSING_FROM, PROCESSING_THRU);
CREATE INDEX IF NOT EXISTS IDX_ORDER_ITEMS_ORDER ON ORDER_ITEMS(ORDER_ID);
CREATE INDEX IF NOT EXISTS IDX_ORDER_ITEMS_PRODUCT ON ORDER_ITEMS(PRODUCT_ID);

-- No INSERT statements for tests - tests will create their own data