package io.github.kotlinreladomo.sample.domain.kotlin

import io.github.kotlinreladomo.core.BiTemporalEntity
import java.math.BigDecimal
import java.time.Instant

/**
 * Kotlin wrapper for Order entity.
 * Note: This is a manual implementation for testing. 
 * In production, this would be generated by the Gradle plugin.
 */
data class OrderKt(
    val orderId: Long,
    val customerId: Long,
    val orderDate: Instant,
    val amount: BigDecimal,
    val status: String,
    val description: String?,
    override val businessDate: Instant,
    override val processingDate: Instant
) : BiTemporalEntity {
    
    companion object {
        fun fromReladomo(order: Any): OrderKt {
            // In a real implementation, this would convert from the Reladomo object
            // For now, we'll create a dummy implementation
            return OrderKt(
                orderId = 1L,
                customerId = 100L,
                orderDate = Instant.now(),
                amount = BigDecimal("999.99"),
                status = "PENDING",
                description = "Test order",
                businessDate = Instant.now(),
                processingDate = Instant.now()
            )
        }
    }
    
    fun toReladomo(): Any {
        // In a real implementation, this would convert to a Reladomo object
        // For now, we'll return a placeholder
        return this
    }
}